version: 2.1
orbs:
  android: circleci/android@2.4.0
executors:
  android-executor:
    docker:
      - image: cimg/android:2024.09
    environment:
      JVM_OPTS: -Xmx3200m
jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: app-debug.apk
      - store_test_results:
          path: app/build/test-results

  unit_tests:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest
      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest
          destination: unit_test_reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
      - build:
          requires:
            - unit_tests